/**
 * This object gets autogenerated by the Gulp configuration. Note that keys meant only for Gulp (e.g., directory)
 * won't get exported here. Only the properties specified are available.
 */
export default {
  title: '',
  notificationTag: '',
  homepage: '',
  feedUrl: '',
  aboutText: '',
  parser: ''
}